### ISSUE TITLE
Not compatible with buffered data store?

### ISSUE THREAD

**Issue by shmerpa** [hiebj/quickfilter#1]
Does this work properly with Ext JS buffered data stores, like if I were to use infinite scrolling or pagination which would fetch a fixed number of records to render at a time? This is a typical thing to do with Ext JS grids and stores with RESTful AJAX proxies. It seems to assume that all filterable records are already rendered and just might not be viewable.

**Comment by hiebj** [comment]
No, this filter is not compatible with a buffered store. In a buffered store, search logic can only be implemented server-side, which will be much more powerful and specific anyway. This is really only a gadget meant to easily mimic that behavior with a small(ish) local dataset. When search is server-side, in my experience it is simple enough to use a simple text field in the UI, or else Ext.ux.grid.plugin.Filter, which works more closely with basic property-value filtering.

If you have a suggestion for a remote filtering feature I would love to hear it.

-jh

-----Original Message-----
